name: Generate Datas

on:
  schedule:
    - cron: "0 */12 * * *"  # Runs every 12 hours
  workflow_dispatch:

jobs:
  build:
    name: Generate contribution snake
    runs-on: ubuntu-latest

    steps:
      # Clone the repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # Generate the contribution snake SVG
      - name: Generate GitHub contribution snake
        uses: Platane/snk@v3
        with:
          github_user_name: himanshugaura
          svg_out_path: dist/github-contribution-grid-snake.svg

      # Debugging step to confirm file was generated
      - name: Show generated files
        run: ls -R dist

      # Push the snake SVG to the output branch
      - name: Push snake to output branch
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
